service: selenium

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  timeout: 600

functions:
  selenium:
    handler: handler.seleniumTest

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux